### ISSUE TITLE
Java API connection problems

### ISSUE THREAD

**Issue by markglh** [softwaremill/reactive-kafka#33]
There's an issue with the Java api, I get this error: 
```
Caused by: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
    at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
    at kafka.consumer.ZookeeperConsumerConnector.connectZk(ZookeeperConsumerConnector.scala:171)
    at kafka.consumer.ZookeeperConsumerConnector.<init>(ZookeeperConsumerConnector.scala:126)
    at kafka.consumer.ZookeeperConsumerConnector.<init>(ZookeeperConsumerConnector.scala:143)
    at kafka.consumer.Consumer$.create(ConsumerConnector.scala:94)
    at kafka.consumer.KafkaConsumer.<init>(KafkaConsumer.scala:12)
    at com.softwaremill.react.kafka.ReactiveKafka.consumerActorProps(ReactiveKafka.scala:174)
    at com.softwaremill.react.kafka.ReactiveKafka.consumerActor(ReactiveKafka.scala:170)
    at com.softwaremill.react.kafka.ReactiveKafka.consumerActor(ReactiveKafka.scala:163)
    at com.softwaremill.react.kafka.ReactiveKafka.consume(ReactiveKafka.scala:152)
```

This is the code I'm using to create the consumer
```java
ConsumerProperties<Byte[], String> consumerProps =
                new PropertiesBuilder.Consumer(zookeeperHost, brokerList, topic, groupName, new StringDecoder(null))
                        .build();

        Publisher<KeyValueKafkaMessage<Byte[], String>> publisher = this.reactiveKafka.consume(consumerProps, actorSystem);

        return Source.from(publisher).map(KeyValueKafkaMessage::msg);
```

I'm still trying to figure out why, will let you know if I make progress - might be in the morning though as I've got to head off soon.

FYI this code seems to fair a little better (connects), although it seems to fail to shutdown
```java
public Source<String, BoxedUnit> createConsumerSource(final String topic, final String groupName, ActorSystem actorSystem) {

        Map<String, String> consumerParams = new HashMap<>();
        consumerParams.put("zookeeper.connect", zookeeperHost);
        consumerParams.put("group.id", groupName);
        ConsumerProperties<String, String> consumerProps = new ConsumerProperties<>(
                toScalaMap(consumerParams),
                topic,
                groupName,
                new StringDecoder(null),
                new StringDecoder(null)
        );

        Publisher<KeyValueKafkaMessage<String, String>> publisher = this.reactiveKafka.consume(consumerProps, actorSystem);

        return Source.from(publisher).map(KeyValueKafkaMessage::msg);
    }

    private static scala.collection.immutable.Map toScalaMap(Map<String, String> javaMap) {
        return new scala.collection.immutable.HashMap<String, String>().$plus$plus(
                JavaConverters.mapAsScalaMapConverter(javaMap).asScala()
        );
    }
```

**Comment by markglh** [comment]
In the `PropertiesBuilder` class we have the following 
```java
public Consumer(String zooKeeperHost, String brokerList, String topic, String groupId, Decoder decoder) {
            super(zooKeeperHost, brokerList, topic);
            this.decoder = decoder;
            this.groupId = groupId;
        }
```

`super` here is calling this:

```java
public BaseProperties(String brokerList, String zooKeeperHost, String topic) {
            this.brokerList = brokerList;
            this.zooKeeperHost = zooKeeperHost;
            this.topic = topic;
        }
```

So `zooKeeperHost` and `brokerList` are reversed.

Changing the consumer to be consistent with the other constructors fixes this:
```java
public Consumer(String brokerList, String zooKeeperHost, String topic, String groupId, Decoder decoder) {
            super(brokerList, zooKeeperHost, topic);
            this.decoder = decoder;
            this.groupId = groupId;
        }
```

**Comment by markglh** [comment]
Fixed here: https://github.com/softwaremill/reactive-kafka/pull/34
