### ISSUE TITLE
Java PropertiesBuilder.java throws NPE

### ISSUE THREAD

**Issue by az-qbradley** [softwaremill/reactive-kafka#49]
https://github.com/softwaremill/reactive-kafka/blob/master/core/src/main/java/com/softwaremill/react/kafka/PropertiesBuilder.java#L131

When this line is triggered, partitionizer is null, and cause NPE thrown at https://github.com/softwaremill/reactive-kafka/blob/ebf7aa417d7e481d4dd1526194d0d15193e11cc4/core/src/main/scala/com/softwaremill/react/kafka/KafkaActorSubscriber.scala#L27

------------------------------------------
[ERROR] [11/08/2015 10:55:08.843] [ReactiveKafka-akka.actor.default-dispatcher-4] [akka://ReactiveKafka/user/$b] null
java.lang.NullPointerException
 at com.softwaremill.react.kafka.KafkaActorSubscriber.com$softwaremill$react$kafka$KafkaActorSubscriber$$processElement(KafkaActorSubscriber.scala:27)
 at com.softwaremill.react.kafka.KafkaActorSubscriber$$anonfun$receive$1.applyOrElse(KafkaActorSubscriber.scala:18)
 at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
 at com.softwaremill.react.kafka.KafkaActorSubscriber.akka$stream$actor$ActorSubscriber$$super$aroundReceive(KafkaActorSubscriber.scala:7)
 at akka.stream.actor.ActorSubscriber$class.aroundReceive(ActorSubscriber.scala:180)
 at com.softwaremill.react.kafka.KafkaActorSubscriber.aroundReceive(KafkaActorSubscriber.scala:7)
 at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
 at akka.actor.ActorCell.invoke(ActorCell.scala:487)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
 at akka.dispatch.Mailbox.run(Mailbox.scala:220)
 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
 at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by kciesielski** [comment]
Thanks, this indeed needs fixing. The NPE occurs only when you create `new PropertiesBuilder.Producer(...)` and pass null `brokerList` or `zooKeepHost`, so a workaround would be to ensure that these two params are not null.

**Comment by az-qbradley** [comment]
Thanks a lot!
