### ISSUE TITLE
sbt core/test does not work on OS X

### ISSUE THREAD

**Issue by akauppi** [softwaremill/reactive-kafka#94]
With commit 445e45ca9340bf60c3aa45bd464cbf29387e84c0

````
$ sbt core/test
````

causes exceptions and gets stuck. I'm running on OS X 10.11.3, with Kafka 0.9.0.0 via Homebrew unofficial package: https://github.com/Homebrew/homebrew/pull/48245

I haven't looked in detail to what could be wrong. I'm expecting `master` should always pass the tests, right?

1. Are others able to reproduce this
2. Is there something I can do about it?

[logs-core-test.txt](https://github.com/softwaremill/reactive-kafka/files/149817/logs-core-test.txt)

**Comment by 13h3r** [comment]
@akauppi tests in master should work. Could you tell which tests are broken? (away form my laptop now)

**Comment by 13h3r** [comment]
I checked tests and they  works for me. Note, that it takes about 20 minutes to complete them on my laptop. Also not that you should allow to auto create new topics in kafka. I updated readme with this small detail.

**Comment by akauppi** [comment]
The log of running the tests is included in the issue.

**Comment by 13h3r** [comment]
There are a lot of errors in logs because a spec tests exceptional situations and a reaction to them. 

As for me your log looks incomplete, because it should ends with summary. Like this:

```
===============================================
Command line suite
Total tests run: 36, Failures: 0, Skips: 20
===============================================

[info] ReactiveKafkaPublisherSpec:
[info] - optional_spec104_mustSignalOnErrorWhenFails
[info] - optional_spec105_emptyStreamMustTerminateBySignallingOnComplete !!! IGNORED !!!
[info] - optional_spec111_maySupportMultiSubscribe !!! IGNORED !!!
[info] - optional_spec111_multicast_mustProduceTheSameElementsInTheSameSequenceToAllOfItsSubscribersWhenRequestingManyUpfront !!! IGNORED !!!
[info] - optional_spec111_multicast_mustProduceTheSameElementsInTheSameSequenceToAllOfItsSubscribersWhenRequestingManyUpfrontAndCompleteAsExpected !!! IGNORED !!!
[info] - optional_spec111_multicast_mustProduceTheSameElementsInTheSameSequenceToAllOfItsSubscribersWhenRequestingOneByOne !!! IGNORED !!!
[info] - required_createPublisher1MustProduceAStreamOfExactly1Element !!! IGNORED !!!
[info] - required_createPublisher3MustProduceAStreamOfExactly3Elements !!! IGNORED !!!
[info] - required_spec101_subscriptionRequestMustResultInTheCorrectNumberOfProducedElements
[info] - required_spec102_maySignalLessThanRequestedAndTerminateSubscription !!! IGNORED !!!
[info] - required_spec105_mustSignalOnCompleteWhenFiniteStreamTerminates !!! IGNORED !!!
[info] - required_spec107_mustNotEmitFurtherSignalsOnceOnCompleteHasBeenSignalled !!! IGNORED !!!
[info] - required_spec109_mayRejectCallsToSubscribeIfPublisherIsUnableOrUnwillingToServeThemRejectionMustTriggerOnErrorAfterOnSubscribe
[info] - required_spec109_mustIssueOnSubscribeForNonNullSubscriber
[info] - required_spec109_subscribeThrowNPEOnNullSubscriber
[info] - required_spec302_mustAllowSynchronousRequestCallsFromOnNextAndOnSubscribe
[info] - required_spec303_mustNotAllowUnboundedRecursion
[info] - required_spec306_afterSubscriptionIsCancelledRequestMustBeNops
[info] - required_spec307_afterSubscriptionIsCancelledAdditionalCancelationsMustBeNops
[info] - required_spec309_requestNegativeNumberMustSignalIllegalArgumentException
[info] - required_spec309_requestZeroMustSignalIllegalArgumentException
[info] - required_spec312_cancelMustMakeThePublisherToEventuallyStopSignaling
[info] - required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber
[info] - required_spec317_mustNotSignalOnErrorWhenPendingAboveLongMaxValue
[info] - required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue !!! IGNORED !!!
[info] - required_spec317_mustSupportAPendingElementCountUpToLongMaxValue !!! IGNORED !!!
[info] - required_validate_boundedDepthOfOnNextAndRequestRecursion
[info] - required_validate_maxElementsFromPublisher
[info] - stochastic_spec103_mustSignalOnMethodsSequentially !!! IGNORED !!!
[info] - untested_spec106_mustConsiderSubscriptionCancelledAfterOnErrorOrOnCompleteHasBeenCalled !!! IGNORED !!!
[info] - untested_spec107_mustNotEmitFurtherSignalsOnceOnErrorHasBeenSignalled !!! IGNORED !!!
[info] - untested_spec108_possiblyCanceledSubscriptionShouldNotReceiveOnErrorOrOnCompleteSignals !!! IGNORED !!!
[info] - untested_spec109_subscribeShouldNotThrowNonFatalThrowable !!! IGNORED !!!
[info] - untested_spec110_rejectASubscriptionRequestIfTheSameSubscriberSubscribesTwice !!! IGNORED !!!
[info] - untested_spec304_requestShouldNotPerformHeavyComputations !!! IGNORED !!!
[info] - untested_spec305_cancelMustNotSynchronouslyPerformHeavyCompuatation !!! IGNORED !!!
[info] ScalaTest
[info] Run completed in 13 minutes, 28 seconds.
[info] Total number of tests run: 16
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 16, failed 0, canceled 0, ignored 20, pending 0
[info] All tests passed.
[info] Passed: Total 16, Failed 0, Errors 0, Passed 16, Ignored 20
[success] Total time: 822 s, completed 28.02.2016 23:27:12
```

Also I did not find any failures in log.

**Comment by akauppi** [comment]
Ok, I was more patient this time and let the tests run. 

You are right, eventually the summary comes up. Only one of the tests failed:

```
- required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber *** FAILED ***
[info]   java.lang.AssertionError: Did not receive expected element within 30000 ms
[info]   at org.testng.Assert.fail(Assert.java:78)
[info]   at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:180)
[info]   at org.reactivestreams.tck.TestEnvironment$Receptacle.next(TestEnvironment.java:878)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:400)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:392)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:388)
[info]   at org.reactivestreams.tck.PublisherVerification$24.apply(PublisherVerification.java:956)
[info]   at org.reactivestreams.tck.PublisherVerification$24.apply(PublisherVerification.java:949)
[info]   at org.reactivestreams.tck.PublisherVerification$25.run(PublisherVerification.java:966)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   ...
[info]   Cause: java.lang.AssertionError: Did not receive expected element within 30000 ms
[info]   at org.testng.Assert.fail(Assert.java:89)
[info]   at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:177)
[info]   at org.reactivestreams.tck.TestEnvironment$Receptacle.next(TestEnvironment.java:878)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:400)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:392)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:388)
[info]   at org.reactivestreams.tck.PublisherVerification$24.apply(PublisherVerification.java:956)
[info]   at org.reactivestreams.tck.PublisherVerification$24.apply(PublisherVerification.java:949)
[info]   at org.reactivestreams.tck.PublisherVerification$25.run(PublisherVerification.java:966)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   ...
```

So I think the real problem was I'm just not used to tests showing stack traces on the log. Please check the above fail log and if it seems fine, I don't mind if you close the issue. The machine is Core i7 Macbook Air (mid 2011).

**Comment by 13h3r** [comment]
What about rerun only this test?

**Comment by kciesielski** [comment]
There are a few tests which take a very long time. They may need bumping timeout in settings. As @13h3r mentioned, some exceptions are expected on the output :)

**Comment by akauppi** [comment]
Ok. Then the instructions on how to bump those timeouts could be clearly stated in the README.

>There are a few tests which take a very long time. They may need bumping timeout in settings. As @13h3r mentioned, some exceptions are expected on the output :)

It seems I'm ending my scouting on reactive-kafka, for now. Good luck with the project.

**Comment by akauppi** [comment]
@13h3r Wasn't able to figure out which command reruns a single test in a multi-project setup.

**Comment by kciesielski** [comment]
@akauppi Thanks for all the input. Good point with adding information on test timeouts to the README. Looks like this "30000" reported in your output is not the timeout I was thinking about. I'm adding an issue to investigate this further.
